name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */6 * * *"  # Atualiza a cada 6 horas
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Gerar a Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: GabrielRossi01
          outputs: |
            dist/snake.svg
            dist/snake-dark.svg?palette=github-dark

      - name: Commit e Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/snake.svg dist/snake-dark.svg
          git commit -m "Atualizando Snake Animation" || echo "Nenhuma alteração para commit"
          git push
